# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31228381615cebf330a1184fe7e86242e326547f1e59b3aed1c1728753a857f7ca39eac59cc3f46db47de5b1af4975a263fb42906f3d03cd2bd98353fa93cb93

test:
  secret_key_base: 1a796e42ad30c2ebeceec32c263f3d9872dc669a53d64a5c209802cffe6c47085cd38d60f0f3ddb9f37a113bccd8a04197e0d3f0657e434f9fa5a76e161b3237

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
